# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Edit_game2.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Edit(object):
    def setupUi(self, Menu):
        Menu.setObjectName("Menu")
        Menu.setWindowModality(QtCore.Qt.ApplicationModal)
        Menu.resize(885, 677)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Menu.sizePolicy().hasHeightForWidth())
        Menu.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(49)
        Menu.setFont(font)
        Menu.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        Menu.setAutoFillBackground(False)
        Menu.setStyleSheet("QWidget {    \n"
"\n"
"    \n"
"    background-color: rgb(26, 65, 90);\n"
"\n"
"}\n"
"/*\n"
"\n"
"background-image: linear-gradient(15deg, #13547a 0%, #80d0c7 100%);\n"
"background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #13547a, stop: .5 #80d0c7);\n"
"background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0.4 #13547a, stop: 0.8 #80d0c7);\n"
"            \n"
"\n"
"*/\n"
"\n"
"/* background-color: rgb(26, 65, 90); */\n"
"\n"
"\n"
"")
        self.Title_Screen = QtWidgets.QLabel(Menu)
        self.Title_Screen.setGeometry(QtCore.QRect(220, 0, 461, 61))
        font = QtGui.QFont()
        font.setFamily("Leelawadee")
        font.setPointSize(32)
        self.Title_Screen.setFont(font)
        self.Title_Screen.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Title_Screen.setAutoFillBackground(False)
        self.Title_Screen.setStyleSheet("color: rgb(255, 255, 255);\n"
"boder:none;")
        self.Title_Screen.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Title_Screen.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Title_Screen.setLineWidth(0)
        self.Title_Screen.setAlignment(QtCore.Qt.AlignCenter)
        self.Title_Screen.setObjectName("Title_Screen")
        self.frame = QtWidgets.QFrame(Menu)
        self.frame.setGeometry(QtCore.QRect(40, 203, 781, 391))
        self.frame.setStyleSheet("/* VERTIVAL SCROLL BAR*/\n"
"QScrollBar:vertical{\n"
"    boder: none;\n"
"    width: 14px;\n"
"    margin: 15px 0 15px 0;\n"
"    border-radius:10px;\n"
"    background-color: rgb(31, 125, 108);\n"
"}\n"
"\n"
"/* HANDLE BAR VERTICAL */\n"
"QScrollBar::handle:vertical {\n"
"    border-radius:4px;\n"
"    min-height:15px;\n"
"    background-color: rgb(31, 79, 108);\n"
"}\n"
"\n"
"/* BUTTON TOP - SCROLLBAR*/\n"
"\n"
"QScrollBar::sub-line:vertical{\n"
"    border:none;    \n"
"    background-color: rgb(255, 255, 255);\n"
"    height: 15px;\n"
"    border-top-left-radius: 5px;\n"
"    border-top-right-radius:5px;\n"
"    subcontrol-position:top;\n"
"    subcontrol-origin: margin;\n"
"    \n"
"}\n"
"\n"
"\n"
"\n"
"/* BUTTON BOTTOM - SCROLLBAR*/\n"
"\n"
"QScrollBar::add-line:vertical{\n"
"    border:none;    \n"
"    background-color: rgb(255, 255, 255);\n"
"    height: 15px;\n"
"    border-bottom-left-radius: 5px;\n"
"    border-bottom-right-radius:5px;\n"
"    subcontrol-position:bottom;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"\n"
"\n"
"/* RESET ARROW */\n"
"\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"     \n"
"     background: none;\n"
"}\n"
"\n"
" QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"     background: none;\n"
"}\n"
"\n"
"QScrollBar::sub-page:vertical {\n"
"background: none;\n"
"}\n"
"\n"
"QScrollBar::add-page:vertical {\n"
"background: none;\n"
"}\n"
"\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setLineWidth(0)
        self.frame.setObjectName("frame")
        self.scrollArea = QtWidgets.QScrollArea(self.frame)
        self.scrollArea.setGeometry(QtCore.QRect(-1, 10, 781, 371))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.scrollArea.setStyleSheet("/* VERTIVAL SCROLL BAR*/\n"
"QScrollBar:vertical{\n"
"    background-color: rgb(31, 125, 108);\n"
"}\n"
"\n"
"\n"
"\n"
"")
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setFrameShadow(QtWidgets.QFrame.Plain)
        self.scrollArea.setLineWidth(0)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 767, 1640))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setContentsMargins(9, 10, 9, 0)
        self.verticalLayout_2.setSpacing(20)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.key1 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.key1.sizePolicy().hasHeightForWidth())
        self.key1.setSizePolicy(sizePolicy)
        self.key1.setMinimumSize(QtCore.QSize(0, 55))
        self.key1.setMaximumSize(QtCore.QSize(16777215, 90))
        self.key1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.key1.setStyleSheet("background-color: rgb(30, 217, 89);\n"
"")
        self.key1.setObjectName("key1")
        self.game_command1 = QtWidgets.QLineEdit(self.key1)
        self.game_command1.setGeometry(QtCore.QRect(10, 6, 251, 43))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.game_command1.sizePolicy().hasHeightForWidth())
        self.game_command1.setSizePolicy(sizePolicy)
        self.game_command1.setMinimumSize(QtCore.QSize(0, 43))
        self.game_command1.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(20)
        self.game_command1.setFont(font)
        self.game_command1.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"border-style: solid;\n"
"border-width: 2px;\n"
"border-color: black;")
        self.game_command1.setInputMask("")
        self.game_command1.setMaxLength(17)
        self.game_command1.setAlignment(QtCore.Qt.AlignCenter)
        self.game_command1.setReadOnly(False)
        self.game_command1.setObjectName("game_command1")
        self.key_1_name = QtWidgets.QLabel(self.key1)
        self.key_1_name.setGeometry(QtCore.QRect(336, 6, 108, 43))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(30)
        self.key_1_name.setFont(font)
        self.key_1_name.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-style: solid;\n"
"border-width: 2px;\n"
"border-color: black;")
        self.key_1_name.setAlignment(QtCore.Qt.AlignCenter)
        self.key_1_name.setObjectName("key_1_name")
        self.checkBoxW = QtWidgets.QCheckBox(self.key1)
        self.checkBoxW.setGeometry(QtCore.QRect(600, 2, 51, 51))
        self.checkBoxW.setStyleSheet("QCheckBox::indicator {\n"
"     width: 40px;\n"
"     height: 40px;\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"    border-color: black;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"  \n"
"      background-color:rgb(7, 113, 240)\n"
"}\n"
"QCheckBox::indicator:unchecked {\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"")
        self.checkBoxW.setText("")
        self.checkBoxW.setIconSize(QtCore.QSize(23, 28))
        self.checkBoxW.setCheckable(True)
        self.checkBoxW.setObjectName("checkBoxW")
        self.verticalLayout_2.addWidget(self.key1)
        self.key2 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.key2.sizePolicy().hasHeightForWidth())
        self.key2.setSizePolicy(sizePolicy)
        self.key2.setMinimumSize(QtCore.QSize(0, 55))
        self.key2.setMaximumSize(QtCore.QSize(16777215, 90))
        self.key2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.key2.setStyleSheet("background-color: rgb(30, 217, 89);\n"
"")
        self.key2.setObjectName("key2")
        self.game_command2 = QtWidgets.QLineEdit(self.key2)
        self.game_command2.setGeometry(QtCore.QRect(10, 6, 251, 43))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.game_command2.sizePolicy().hasHeightForWidth())
        self.game_command2.setSizePolicy(sizePolicy)
        self.game_command2.setMinimumSize(QtCore.QSize(0, 43))
        self.game_command2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(20)
        self.game_command2.setFont(font)
        self.game_command2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"border-style: solid;\n"
"border-width: 2px;\n"
"border-color: black;")
        self.game_command2.setInputMask("")
        self.game_command2.setMaxLength(16)
        self.game_command2.setAlignment(QtCore.Qt.AlignCenter)
        self.game_command2.setObjectName("game_command2")
        self.key_2_name = QtWidgets.QLabel(self.key2)
        self.key_2_name.setGeometry(QtCore.QRect(336, 6, 108, 43))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(30)
        self.key_2_name.setFont(font)
        self.key_2_name.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-style: solid;\n"
"border-width: 2px;\n"
"border-color: black;")
        self.key_2_name.setAlignment(QtCore.Qt.AlignCenter)
        self.key_2_name.setObjectName("key_2_name")
        self.checkBoxS = QtWidgets.QCheckBox(self.key2)
        self.checkBoxS.setGeometry(QtCore.QRect(600, 2, 51, 51))
        self.checkBoxS.setStyleSheet("QCheckBox::indicator {\n"
"     width: 40px;\n"
"     height: 40px;\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"    border-color: black;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"   background-color: rgb(7, 113, 240);\n"
"}\n"
"QCheckBox::indicator:unchecked {\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.checkBoxS.setText("")
        self.checkBoxS.setIconSize(QtCore.QSize(23, 28))
        self.checkBoxS.setCheckable(True)
        self.checkBoxS.setObjectName("checkBoxS")
        self.verticalLayout_2.addWidget(self.key2)
        self.key3 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.key3.sizePolicy().hasHeightForWidth())
        self.key3.setSizePolicy(sizePolicy)
        self.key3.setMinimumSize(QtCore.QSize(0, 55))
        self.key3.setMaximumSize(QtCore.QSize(16777215, 90))
        self.key3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.key3.setStyleSheet("background-color: rgb(30, 217, 89);\n"
"")
        self.key3.setObjectName("key3")
        self.game_command3 = QtWidgets.QLineEdit(self.key3)
        self.game_command3.setGeometry(QtCore.QRect(10, 6, 251, 43))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.game_command3.sizePolicy().hasHeightForWidth())
        self.game_command3.setSizePolicy(sizePolicy)
        self.game_command3.setMinimumSize(QtCore.QSize(0, 43))
        self.game_command3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(20)
        self.game_command3.setFont(font)
        self.game_command3.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"border-style: solid;\n"
"border-width: 2px;\n"
"border-color: black;")
        self.game_command3.setInputMask("")
        self.game_command3.setMaxLength(16)
        self.game_command3.setAlignment(QtCore.Qt.AlignCenter)
        self.game_command3.setObjectName("game_command3")
        self.key_3_name = QtWidgets.QLabel(self.key3)
        self.key_3_name.setGeometry(QtCore.QRect(336, 6, 108, 43))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(30)
        self.key_3_name.setFont(font)
        self.key_3_name.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-style: solid;\n"
"border-width: 2px;\n"
"border-color: black;")
        self.key_3_name.setAlignment(QtCore.Qt.AlignCenter)
        self.key_3_name.setObjectName("key_3_name")
        self.checkBoxA = QtWidgets.QCheckBox(self.key3)
        self.checkBoxA.setGeometry(QtCore.QRect(600, 2, 51, 51))
        self.checkBoxA.setStyleSheet("QCheckBox::indicator {\n"
"     width: 40px;\n"
"     height: 40px;\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"    border-color: black;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"  background-color: rgb(7, 113, 240);\n"
"}\n"
"QCheckBox::indicator:unchecked {\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.checkBoxA.setText("")
        self.checkBoxA.setIconSize(QtCore.QSize(23, 28))
        self.checkBoxA.setCheckable(True)
        self.checkBoxA.setObjectName("checkBoxA")
        self.verticalLayout_2.addWidget(self.key3)
        self.key4 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.key4.sizePolicy().hasHeightForWidth())
        self.key4.setSizePolicy(sizePolicy)
        self.key4.setMinimumSize(QtCore.QSize(0, 55))
        self.key4.setMaximumSize(QtCore.QSize(16777215, 90))
        self.key4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.key4.setStyleSheet("background-color: rgb(30, 217, 89);\n"
"")
        self.key4.setObjectName("key4")
        self.game_command4 = QtWidgets.QLineEdit(self.key4)
        self.game_command4.setGeometry(QtCore.QRect(10, 6, 251, 43))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.game_command4.sizePolicy().hasHeightForWidth())
        self.game_command4.setSizePolicy(sizePolicy)
        self.game_command4.setMinimumSize(QtCore.QSize(0, 43))
        self.game_command4.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(20)
        self.game_command4.setFont(font)
        self.game_command4.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"border-style: solid;\n"
"border-width: 2px;\n"
"border-color: black;")
        self.game_command4.setInputMask("")
        self.game_command4.setMaxLength(16)
        self.game_command4.setAlignment(QtCore.Qt.AlignCenter)
        self.game_command4.setObjectName("game_command4")
        self.key_4_name = QtWidgets.QLabel(self.key4)
        self.key_4_name.setGeometry(QtCore.QRect(336, 6, 108, 43))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(30)
        self.key_4_name.setFont(font)
        self.key_4_name.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-style: solid;\n"
"border-width: 2px;\n"
"border-color: black;")
        self.key_4_name.setAlignment(QtCore.Qt.AlignCenter)
        self.key_4_name.setObjectName("key_4_name")
        self.checkBoxD = QtWidgets.QCheckBox(self.key4)
        self.checkBoxD.setGeometry(QtCore.QRect(600, 2, 51, 51))
        self.checkBoxD.setStyleSheet("QCheckBox::indicator {\n"
"     width: 40px;\n"
"     height: 40px;\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"    border-color: black;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"background-color: rgb(7, 113, 240);\n"
"}\n"
"QCheckBox::indicator:unchecked {\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.checkBoxD.setText("")
        self.checkBoxD.setIconSize(QtCore.QSize(23, 28))
        self.checkBoxD.setCheckable(True)
        self.checkBoxD.setObjectName("checkBoxD")
        self.verticalLayout_2.addWidget(self.key4)
        self.key5 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.key5.sizePolicy().hasHeightForWidth())
        self.key5.setSizePolicy(sizePolicy)
        self.key5.setMinimumSize(QtCore.QSize(0, 55))
        self.key5.setMaximumSize(QtCore.QSize(16777215, 90))
        self.key5.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.key5.setStyleSheet("background-color: rgb(30, 217, 89);\n"
"")
        self.key5.setObjectName("key5")
        self.game_command5 = QtWidgets.QLineEdit(self.key5)
        self.game_command5.setGeometry(QtCore.QRect(10, 6, 251, 43))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.game_command5.sizePolicy().hasHeightForWidth())
        self.game_command5.setSizePolicy(sizePolicy)
        self.game_command5.setMinimumSize(QtCore.QSize(0, 43))
        self.game_command5.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.game_command5.setFont(font)
        self.game_command5.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"border-style: solid;\n"
"border-width: 2px;\n"
"border-color: black;")
        self.game_command5.setInputMask("")
        self.game_command5.setMaxLength(16)
        self.game_command5.setAlignment(QtCore.Qt.AlignCenter)
        self.game_command5.setObjectName("game_command5")
        self.key_5_name = QtWidgets.QLabel(self.key5)
        self.key_5_name.setGeometry(QtCore.QRect(336, 6, 108, 43))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(30)
        self.key_5_name.setFont(font)
        self.key_5_name.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-style: solid;\n"
"border-width: 2px;\n"
"border-color: black;")
        self.key_5_name.setAlignment(QtCore.Qt.AlignCenter)
        self.key_5_name.setObjectName("key_5_name")
        self.checkBox_Q = QtWidgets.QCheckBox(self.key5)
        self.checkBox_Q.setGeometry(QtCore.QRect(600, 2, 51, 51))
        self.checkBox_Q.setStyleSheet("QCheckBox::indicator {\n"
"     width: 40px;\n"
"     height: 40px;\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"    border-color: black;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"  background-color: rgb(7, 113, 240);\n"
"}\n"
"QCheckBox::indicator:unchecked {\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.checkBox_Q.setText("")
        self.checkBox_Q.setIconSize(QtCore.QSize(23, 28))
        self.checkBox_Q.setCheckable(True)
        self.checkBox_Q.setObjectName("checkBox_Q")
        self.verticalLayout_2.addWidget(self.key5)
        self.key6 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.key6.sizePolicy().hasHeightForWidth())
        self.key6.setSizePolicy(sizePolicy)
        self.key6.setMinimumSize(QtCore.QSize(0, 55))
        self.key6.setMaximumSize(QtCore.QSize(16777215, 90))
        self.key6.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.key6.setStyleSheet("background-color: rgb(30, 217, 89);\n"
"")
        self.key6.setObjectName("key6")
        self.game_command6 = QtWidgets.QLineEdit(self.key6)
        self.game_command6.setGeometry(QtCore.QRect(10, 6, 251, 43))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.game_command6.sizePolicy().hasHeightForWidth())
        self.game_command6.setSizePolicy(sizePolicy)
        self.game_command6.setMinimumSize(QtCore.QSize(0, 43))
        self.game_command6.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(20)
        self.game_command6.setFont(font)
        self.game_command6.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"border-style: solid;\n"
"border-width: 2px;\n"
"border-color: black;")
        self.game_command6.setInputMask("")
        self.game_command6.setMaxLength(16)
        self.game_command6.setAlignment(QtCore.Qt.AlignCenter)
        self.game_command6.setObjectName("game_command6")
        self.key_6_name = QtWidgets.QLabel(self.key6)
        self.key_6_name.setGeometry(QtCore.QRect(336, 6, 108, 43))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(30)
        self.key_6_name.setFont(font)
        self.key_6_name.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-style: solid;\n"
"border-width: 2px;\n"
"border-color: black;")
        self.key_6_name.setAlignment(QtCore.Qt.AlignCenter)
        self.key_6_name.setObjectName("key_6_name")
        self.checkBox_E = QtWidgets.QCheckBox(self.key6)
        self.checkBox_E.setGeometry(QtCore.QRect(600, 2, 51, 51))
        self.checkBox_E.setStyleSheet("QCheckBox::indicator {\n"
"     width: 40px;\n"
"     height: 40px;\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"    border-color: black;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"  background-color: rgb(7, 113, 240);\n"
"}\n"
"QCheckBox::indicator:unchecked {\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.checkBox_E.setText("")
        self.checkBox_E.setIconSize(QtCore.QSize(23, 28))
        self.checkBox_E.setCheckable(True)
        self.checkBox_E.setObjectName("checkBox_E")
        self.verticalLayout_2.addWidget(self.key6)
        self.key7 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.key7.sizePolicy().hasHeightForWidth())
        self.key7.setSizePolicy(sizePolicy)
        self.key7.setMinimumSize(QtCore.QSize(0, 55))
        self.key7.setMaximumSize(QtCore.QSize(16777215, 90))
        self.key7.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.key7.setStyleSheet("background-color: rgb(30, 217, 89);\n"
"")
        self.key7.setObjectName("key7")
        self.game_command7 = QtWidgets.QLineEdit(self.key7)
        self.game_command7.setGeometry(QtCore.QRect(10, 6, 251, 43))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.game_command7.sizePolicy().hasHeightForWidth())
        self.game_command7.setSizePolicy(sizePolicy)
        self.game_command7.setMinimumSize(QtCore.QSize(0, 43))
        self.game_command7.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(20)
        self.game_command7.setFont(font)
        self.game_command7.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"border-style: solid;\n"
"border-width: 2px;\n"
"border-color: black;")
        self.game_command7.setInputMask("")
        self.game_command7.setMaxLength(16)
        self.game_command7.setAlignment(QtCore.Qt.AlignCenter)
        self.game_command7.setObjectName("game_command7")
        self.key_7_name = QtWidgets.QLabel(self.key7)
        self.key_7_name.setGeometry(QtCore.QRect(336, 6, 108, 43))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(30)
        self.key_7_name.setFont(font)
        self.key_7_name.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-style: solid;\n"
"border-width: 2px;\n"
"border-color: black;")
        self.key_7_name.setAlignment(QtCore.Qt.AlignCenter)
        self.key_7_name.setObjectName("key_7_name")
        self.checkBoxR_3 = QtWidgets.QCheckBox(self.key7)
        self.checkBoxR_3.setGeometry(QtCore.QRect(600, 2, 51, 51))
        self.checkBoxR_3.setStyleSheet("QCheckBox::indicator {\n"
"     width: 40px;\n"
"     height: 40px;\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"    border-color: black;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"  background-color: rgb(7, 113, 240);\n"
"}\n"
"QCheckBox::indicator:unchecked {\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.checkBoxR_3.setText("")
        self.checkBoxR_3.setIconSize(QtCore.QSize(23, 28))
        self.checkBoxR_3.setCheckable(True)
        self.checkBoxR_3.setObjectName("checkBoxR_3")
        self.verticalLayout_2.addWidget(self.key7)
        self.key8 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.key8.sizePolicy().hasHeightForWidth())
        self.key8.setSizePolicy(sizePolicy)
        self.key8.setMinimumSize(QtCore.QSize(0, 55))
        self.key8.setMaximumSize(QtCore.QSize(16777215, 90))
        self.key8.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.key8.setStyleSheet("background-color: rgb(30, 217, 89);\n"
"")
        self.key8.setObjectName("key8")
        self.game_command8 = QtWidgets.QLineEdit(self.key8)
        self.game_command8.setGeometry(QtCore.QRect(10, 6, 251, 43))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.game_command8.sizePolicy().hasHeightForWidth())
        self.game_command8.setSizePolicy(sizePolicy)
        self.game_command8.setMinimumSize(QtCore.QSize(0, 43))
        self.game_command8.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(20)
        self.game_command8.setFont(font)
        self.game_command8.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"border-style: solid;\n"
"border-width: 2px;\n"
"border-color: black;")
        self.game_command8.setInputMask("")
        self.game_command8.setMaxLength(16)
        self.game_command8.setAlignment(QtCore.Qt.AlignCenter)
        self.game_command8.setObjectName("game_command8")
        self.key_8_name = QtWidgets.QLabel(self.key8)
        self.key_8_name.setGeometry(QtCore.QRect(336, 6, 108, 43))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(30)
        self.key_8_name.setFont(font)
        self.key_8_name.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-style: solid;\n"
"border-width: 2px;\n"
"border-color: black;")
        self.key_8_name.setAlignment(QtCore.Qt.AlignCenter)
        self.key_8_name.setObjectName("key_8_name")
        self.checkBoxT = QtWidgets.QCheckBox(self.key8)
        self.checkBoxT.setGeometry(QtCore.QRect(600, 2, 51, 51))
        self.checkBoxT.setStyleSheet("QCheckBox::indicator {\n"
"     width: 40px;\n"
"     height: 40px;\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"    border-color: black;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"  background-color: rgb(7, 113, 240);\n"
"}\n"
"QCheckBox::indicator:unchecked {\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.checkBoxT.setText("")
        self.checkBoxT.setIconSize(QtCore.QSize(23, 28))
        self.checkBoxT.setCheckable(True)
        self.checkBoxT.setObjectName("checkBoxT")
        self.verticalLayout_2.addWidget(self.key8)
        self.key9 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.key9.sizePolicy().hasHeightForWidth())
        self.key9.setSizePolicy(sizePolicy)
        self.key9.setMinimumSize(QtCore.QSize(0, 55))
        self.key9.setMaximumSize(QtCore.QSize(16777215, 90))
        self.key9.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.key9.setStyleSheet("background-color: rgb(30, 217, 89);\n"
"")
        self.key9.setObjectName("key9")
        self.game_command9 = QtWidgets.QLineEdit(self.key9)
        self.game_command9.setGeometry(QtCore.QRect(10, 6, 251, 43))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.game_command9.sizePolicy().hasHeightForWidth())
        self.game_command9.setSizePolicy(sizePolicy)
        self.game_command9.setMinimumSize(QtCore.QSize(0, 43))
        self.game_command9.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(20)
        self.game_command9.setFont(font)
        self.game_command9.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"border-style: solid;\n"
"border-width: 2px;\n"
"border-color: black;")
        self.game_command9.setInputMask("")
        self.game_command9.setMaxLength(16)
        self.game_command9.setAlignment(QtCore.Qt.AlignCenter)
        self.game_command9.setObjectName("game_command9")
        self.key_9_name = QtWidgets.QLabel(self.key9)
        self.key_9_name.setGeometry(QtCore.QRect(336, 6, 108, 43))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(30)
        self.key_9_name.setFont(font)
        self.key_9_name.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-style: solid;\n"
"border-width: 2px;\n"
"border-color: black;")
        self.key_9_name.setText("")
        self.key_9_name.setTextFormat(QtCore.Qt.PlainText)
        self.key_9_name.setPixmap(QtGui.QPixmap("image/espace_Icon.png"))
        self.key_9_name.setScaledContents(True)
        self.key_9_name.setAlignment(QtCore.Qt.AlignCenter)
        self.key_9_name.setWordWrap(False)
        self.key_9_name.setObjectName("key_9_name")
        self.checkBoxEspace = QtWidgets.QCheckBox(self.key9)
        self.checkBoxEspace.setGeometry(QtCore.QRect(600, 2, 51, 51))
        self.checkBoxEspace.setStyleSheet("QCheckBox::indicator {\n"
"     width: 40px;\n"
"     height: 40px;\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"    border-color: black;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
" background-color: rgb(7, 113, 240);\n"
"}\n"
"QCheckBox::indicator:unchecked {\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.checkBoxEspace.setText("")
        self.checkBoxEspace.setIconSize(QtCore.QSize(23, 28))
        self.checkBoxEspace.setCheckable(True)
        self.checkBoxEspace.setObjectName("checkBoxEspace")
        self.verticalLayout_2.addWidget(self.key9)
        self.key10 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.key10.sizePolicy().hasHeightForWidth())
        self.key10.setSizePolicy(sizePolicy)
        self.key10.setMinimumSize(QtCore.QSize(0, 55))
        self.key10.setMaximumSize(QtCore.QSize(16777215, 90))
        self.key10.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.key10.setStyleSheet("background-color: rgb(30, 217, 89);\n"
"")
        self.key10.setObjectName("key10")
        self.game_command10 = QtWidgets.QLineEdit(self.key10)
        self.game_command10.setGeometry(QtCore.QRect(10, 6, 251, 43))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.game_command10.sizePolicy().hasHeightForWidth())
        self.game_command10.setSizePolicy(sizePolicy)
        self.game_command10.setMinimumSize(QtCore.QSize(0, 43))
        self.game_command10.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(20)
        self.game_command10.setFont(font)
        self.game_command10.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"border-style: solid;\n"
"border-width: 2px;\n"
"border-color: black;")
        self.game_command10.setInputMask("")
        self.game_command10.setMaxLength(16)
        self.game_command10.setAlignment(QtCore.Qt.AlignCenter)
        self.game_command10.setObjectName("game_command10")
        self.key_10_name = QtWidgets.QLabel(self.key10)
        self.key_10_name.setGeometry(QtCore.QRect(336, 6, 108, 43))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(30)
        self.key_10_name.setFont(font)
        self.key_10_name.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-style: solid;\n"
"border-width: 2px;\n"
"border-color: black;")
        self.key_10_name.setAlignment(QtCore.Qt.AlignCenter)
        self.key_10_name.setObjectName("key_10_name")
        self.checkBoxCtrl = QtWidgets.QCheckBox(self.key10)
        self.checkBoxCtrl.setGeometry(QtCore.QRect(600, 2, 51, 51))
        self.checkBoxCtrl.setStyleSheet("QCheckBox::indicator {\n"
"     width: 40px;\n"
"     height: 40px;\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"    border-color: black;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"   \n"
"    background-color: rgb(7, 113, 240);\n"
"}\n"
"QCheckBox::indicator:unchecked {\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.checkBoxCtrl.setText("")
        self.checkBoxCtrl.setIconSize(QtCore.QSize(23, 28))
        self.checkBoxCtrl.setCheckable(True)
        self.checkBoxCtrl.setObjectName("checkBoxCtrl")
        self.verticalLayout_2.addWidget(self.key10)
        self.key11 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.key11.sizePolicy().hasHeightForWidth())
        self.key11.setSizePolicy(sizePolicy)
        self.key11.setMinimumSize(QtCore.QSize(0, 55))
        self.key11.setMaximumSize(QtCore.QSize(16777215, 90))
        self.key11.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.key11.setStyleSheet("background-color: rgb(30, 217, 89);\n"
"")
        self.key11.setObjectName("key11")
        self.game_command11 = QtWidgets.QLineEdit(self.key11)
        self.game_command11.setGeometry(QtCore.QRect(10, 6, 251, 43))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.game_command11.sizePolicy().hasHeightForWidth())
        self.game_command11.setSizePolicy(sizePolicy)
        self.game_command11.setMinimumSize(QtCore.QSize(0, 43))
        self.game_command11.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(20)
        self.game_command11.setFont(font)
        self.game_command11.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"border-style: solid;\n"
"border-width: 2px;\n"
"border-color: black;")
        self.game_command11.setInputMask("")
        self.game_command11.setMaxLength(16)
        self.game_command11.setAlignment(QtCore.Qt.AlignCenter)
        self.game_command11.setObjectName("game_command11")
        self.key_11_name = QtWidgets.QLabel(self.key11)
        self.key_11_name.setGeometry(QtCore.QRect(336, 6, 108, 43))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(30)
        self.key_11_name.setFont(font)
        self.key_11_name.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-style: solid;\n"
"border-width: 2px;\n"
"border-color: black;\n"
"")
        self.key_11_name.setText("")
        self.key_11_name.setPixmap(QtGui.QPixmap("image/shitf_icon.png"))
        self.key_11_name.setScaledContents(True)
        self.key_11_name.setAlignment(QtCore.Qt.AlignCenter)
        self.key_11_name.setObjectName("key_11_name")
        self.checkBoxShift = QtWidgets.QCheckBox(self.key11)
        self.checkBoxShift.setGeometry(QtCore.QRect(600, 2, 51, 51))
        self.checkBoxShift.setStyleSheet("QCheckBox::indicator {\n"
"     width: 40px;\n"
"     height: 40px;\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"    border-color: black;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color: rgb(7, 113, 240);\n"
"}\n"
"QCheckBox::indicator:unchecked {\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.checkBoxShift.setText("")
        self.checkBoxShift.setIconSize(QtCore.QSize(23, 28))
        self.checkBoxShift.setCheckable(True)
        self.checkBoxShift.setObjectName("checkBoxShift")
        self.verticalLayout_2.addWidget(self.key11)
        self.key12 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.key12.sizePolicy().hasHeightForWidth())
        self.key12.setSizePolicy(sizePolicy)
        self.key12.setMinimumSize(QtCore.QSize(0, 55))
        self.key12.setMaximumSize(QtCore.QSize(16777215, 90))
        self.key12.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.key12.setStyleSheet("background-color: rgb(30, 217, 89);\n"
"")
        self.key12.setObjectName("key12")
        self.game_command12 = QtWidgets.QLineEdit(self.key12)
        self.game_command12.setGeometry(QtCore.QRect(10, 6, 251, 43))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.game_command12.sizePolicy().hasHeightForWidth())
        self.game_command12.setSizePolicy(sizePolicy)
        self.game_command12.setMinimumSize(QtCore.QSize(0, 43))
        self.game_command12.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(20)
        self.game_command12.setFont(font)
        self.game_command12.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"border-style: solid;\n"
"border-width: 2px;\n"
"border-color: black;")
        self.game_command12.setInputMask("")
        self.game_command12.setMaxLength(16)
        self.game_command12.setAlignment(QtCore.Qt.AlignCenter)
        self.game_command12.setObjectName("game_command12")
        self.key_12_name = QtWidgets.QLabel(self.key12)
        self.key_12_name.setGeometry(QtCore.QRect(336, 6, 108, 43))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(30)
        self.key_12_name.setFont(font)
        self.key_12_name.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-style: solid;\n"
"border-width: 2px;\n"
"border-color: black;")
        self.key_12_name.setScaledContents(False)
        self.key_12_name.setAlignment(QtCore.Qt.AlignCenter)
        self.key_12_name.setObjectName("key_12_name")
        self.checkBoxTab = QtWidgets.QCheckBox(self.key12)
        self.checkBoxTab.setGeometry(QtCore.QRect(600, 2, 51, 51))
        self.checkBoxTab.setStyleSheet("QCheckBox::indicator {\n"
"     width: 40px;\n"
"     height: 40px;\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"    border-color: black;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
" background-color: rgb(7, 113, 240);\n"
"}\n"
"QCheckBox::indicator:unchecked {\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.checkBoxTab.setText("")
        self.checkBoxTab.setIconSize(QtCore.QSize(23, 28))
        self.checkBoxTab.setCheckable(True)
        self.checkBoxTab.setObjectName("checkBoxTab")
        self.verticalLayout_2.addWidget(self.key12)
        self.key13 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.key13.sizePolicy().hasHeightForWidth())
        self.key13.setSizePolicy(sizePolicy)
        self.key13.setMinimumSize(QtCore.QSize(0, 55))
        self.key13.setMaximumSize(QtCore.QSize(16777215, 90))
        self.key13.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.key13.setStyleSheet("background-color: rgb(30, 217, 89);\n"
"")
        self.key13.setObjectName("key13")
        self.game_command13 = QtWidgets.QLineEdit(self.key13)
        self.game_command13.setGeometry(QtCore.QRect(10, 6, 251, 43))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.game_command13.sizePolicy().hasHeightForWidth())
        self.game_command13.setSizePolicy(sizePolicy)
        self.game_command13.setMinimumSize(QtCore.QSize(0, 43))
        self.game_command13.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(20)
        self.game_command13.setFont(font)
        self.game_command13.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"border-style: solid;\n"
"border-width: 2px;\n"
"border-color: black;")
        self.game_command13.setInputMask("")
        self.game_command13.setMaxLength(16)
        self.game_command13.setAlignment(QtCore.Qt.AlignCenter)
        self.game_command13.setObjectName("game_command13")
        self.key_13_name = QtWidgets.QLabel(self.key13)
        self.key_13_name.setGeometry(QtCore.QRect(336, 6, 108, 43))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(30)
        self.key_13_name.setFont(font)
        self.key_13_name.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-style: solid;\n"
"border-width: 2px;\n"
"border-color: black;")
        self.key_13_name.setAlignment(QtCore.Qt.AlignCenter)
        self.key_13_name.setObjectName("key_13_name")
        self.checkBoxZ = QtWidgets.QCheckBox(self.key13)
        self.checkBoxZ.setGeometry(QtCore.QRect(600, 2, 51, 51))
        self.checkBoxZ.setStyleSheet("QCheckBox::indicator {\n"
"     width: 40px;\n"
"     height: 40px;\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"    border-color: black;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"  background-color: rgb(7, 113, 240);\n"
"}\n"
"QCheckBox::indicator:unchecked {\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.checkBoxZ.setText("")
        self.checkBoxZ.setIconSize(QtCore.QSize(23, 28))
        self.checkBoxZ.setCheckable(True)
        self.checkBoxZ.setObjectName("checkBoxZ")
        self.verticalLayout_2.addWidget(self.key13)
        self.key14 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.key14.sizePolicy().hasHeightForWidth())
        self.key14.setSizePolicy(sizePolicy)
        self.key14.setMinimumSize(QtCore.QSize(0, 55))
        self.key14.setMaximumSize(QtCore.QSize(16777215, 90))
        self.key14.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.key14.setStyleSheet("background-color: rgb(30, 217, 89);\n"
"")
        self.key14.setObjectName("key14")
        self.game_command14 = QtWidgets.QLineEdit(self.key14)
        self.game_command14.setGeometry(QtCore.QRect(10, 6, 251, 43))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.game_command14.sizePolicy().hasHeightForWidth())
        self.game_command14.setSizePolicy(sizePolicy)
        self.game_command14.setMinimumSize(QtCore.QSize(0, 43))
        self.game_command14.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(20)
        self.game_command14.setFont(font)
        self.game_command14.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"border-style: solid;\n"
"border-width: 2px;\n"
"border-color: black;")
        self.game_command14.setInputMask("")
        self.game_command14.setMaxLength(16)
        self.game_command14.setAlignment(QtCore.Qt.AlignCenter)
        self.game_command14.setObjectName("game_command14")
        self.key_14_name = QtWidgets.QLabel(self.key14)
        self.key_14_name.setGeometry(QtCore.QRect(336, 6, 108, 43))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(30)
        self.key_14_name.setFont(font)
        self.key_14_name.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-style: solid;\n"
"border-width: 2px;\n"
"border-color: black;")
        self.key_14_name.setAlignment(QtCore.Qt.AlignCenter)
        self.key_14_name.setObjectName("key_14_name")
        self.checkBoxX = QtWidgets.QCheckBox(self.key14)
        self.checkBoxX.setGeometry(QtCore.QRect(600, 2, 51, 51))
        self.checkBoxX.setStyleSheet("QCheckBox::indicator {\n"
"     width: 40px;\n"
"     height: 40px;\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"    border-color: black;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"  background-color: rgb(7, 113, 240);\n"
"}\n"
"QCheckBox::indicator:unchecked {\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"")
        self.checkBoxX.setText("")
        self.checkBoxX.setIconSize(QtCore.QSize(23, 28))
        self.checkBoxX.setCheckable(True)
        self.checkBoxX.setObjectName("checkBoxX")
        self.verticalLayout_2.addWidget(self.key14)
        self.key15 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.key15.sizePolicy().hasHeightForWidth())
        self.key15.setSizePolicy(sizePolicy)
        self.key15.setMinimumSize(QtCore.QSize(0, 55))
        self.key15.setMaximumSize(QtCore.QSize(16777215, 90))
        self.key15.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.key15.setStyleSheet("background-color: rgb(30, 217, 89);\n"
"")
        self.key15.setObjectName("key15")
        self.game_command15 = QtWidgets.QLineEdit(self.key15)
        self.game_command15.setGeometry(QtCore.QRect(10, 6, 251, 43))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.game_command15.sizePolicy().hasHeightForWidth())
        self.game_command15.setSizePolicy(sizePolicy)
        self.game_command15.setMinimumSize(QtCore.QSize(0, 43))
        self.game_command15.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(20)
        self.game_command15.setFont(font)
        self.game_command15.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"border-style: solid;\n"
"border-width: 2px;\n"
"border-color: black;")
        self.game_command15.setInputMask("")
        self.game_command15.setMaxLength(16)
        self.game_command15.setAlignment(QtCore.Qt.AlignCenter)
        self.game_command15.setObjectName("game_command15")
        self.key_15_name = QtWidgets.QLabel(self.key15)
        self.key_15_name.setGeometry(QtCore.QRect(336, 6, 108, 43))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(30)
        self.key_15_name.setFont(font)
        self.key_15_name.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-style: solid;\n"
"border-width: 2px;\n"
"border-color: black;")
        self.key_15_name.setAlignment(QtCore.Qt.AlignCenter)
        self.key_15_name.setObjectName("key_15_name")
        self.checkBoxC = QtWidgets.QCheckBox(self.key15)
        self.checkBoxC.setGeometry(QtCore.QRect(600, 2, 51, 51))
        self.checkBoxC.setStyleSheet("QCheckBox::indicator {\n"
"     width: 40px;\n"
"     height: 40px;\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"    border-color: black;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"  background-color: rgb(7, 113, 240);\n"
"}\n"
"QCheckBox::indicator:unchecked {\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.checkBoxC.setText("")
        self.checkBoxC.setIconSize(QtCore.QSize(23, 28))
        self.checkBoxC.setCheckable(True)
        self.checkBoxC.setObjectName("checkBoxC")
        self.verticalLayout_2.addWidget(self.key15)
        self.key16 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.key16.sizePolicy().hasHeightForWidth())
        self.key16.setSizePolicy(sizePolicy)
        self.key16.setMinimumSize(QtCore.QSize(0, 55))
        self.key16.setMaximumSize(QtCore.QSize(16777215, 90))
        self.key16.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.key16.setStyleSheet("background-color: rgb(30, 217, 89);\n"
"")
        self.key16.setObjectName("key16")
        self.game_command16 = QtWidgets.QLineEdit(self.key16)
        self.game_command16.setGeometry(QtCore.QRect(10, 6, 251, 43))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.game_command16.sizePolicy().hasHeightForWidth())
        self.game_command16.setSizePolicy(sizePolicy)
        self.game_command16.setMinimumSize(QtCore.QSize(0, 43))
        self.game_command16.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(20)
        self.game_command16.setFont(font)
        self.game_command16.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"border-style: solid;\n"
"border-width: 2px;\n"
"border-color: black;")
        self.game_command16.setInputMask("")
        self.game_command16.setMaxLength(16)
        self.game_command16.setAlignment(QtCore.Qt.AlignCenter)
        self.game_command16.setObjectName("game_command16")
        self.key_16_name = QtWidgets.QLabel(self.key16)
        self.key_16_name.setGeometry(QtCore.QRect(336, 6, 108, 43))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(30)
        self.key_16_name.setFont(font)
        self.key_16_name.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-style: solid;\n"
"border-width: 2px;\n"
"border-color: black;")
        self.key_16_name.setAlignment(QtCore.Qt.AlignCenter)
        self.key_16_name.setObjectName("key_16_name")
        self.checkBoxV = QtWidgets.QCheckBox(self.key16)
        self.checkBoxV.setGeometry(QtCore.QRect(600, 2, 51, 51))
        self.checkBoxV.setStyleSheet("QCheckBox::indicator {\n"
"     width: 40px;\n"
"     height: 40px;\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"    border-color: black;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"  background-color: rgb(7, 113, 240);\n"
"}\n"
"QCheckBox::indicator:unchecked {\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.checkBoxV.setText("")
        self.checkBoxV.setIconSize(QtCore.QSize(23, 28))
        self.checkBoxV.setCheckable(True)
        self.checkBoxV.setObjectName("checkBoxV")
        self.verticalLayout_2.addWidget(self.key16)
        self.key17 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.key17.sizePolicy().hasHeightForWidth())
        self.key17.setSizePolicy(sizePolicy)
        self.key17.setMinimumSize(QtCore.QSize(0, 55))
        self.key17.setMaximumSize(QtCore.QSize(16777215, 90))
        self.key17.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.key17.setStyleSheet("background-color: rgb(30, 217, 89);\n"
"")
        self.key17.setObjectName("key17")
        self.game_command17 = QtWidgets.QLineEdit(self.key17)
        self.game_command17.setGeometry(QtCore.QRect(10, 6, 251, 43))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.game_command17.sizePolicy().hasHeightForWidth())
        self.game_command17.setSizePolicy(sizePolicy)
        self.game_command17.setMinimumSize(QtCore.QSize(0, 43))
        self.game_command17.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(20)
        self.game_command17.setFont(font)
        self.game_command17.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"border-style: solid;\n"
"border-width: 2px;\n"
"border-color: black;")
        self.game_command17.setInputMask("")
        self.game_command17.setMaxLength(16)
        self.game_command17.setAlignment(QtCore.Qt.AlignCenter)
        self.game_command17.setObjectName("game_command17")
        self.key_17_name = QtWidgets.QLabel(self.key17)
        self.key_17_name.setGeometry(QtCore.QRect(336, 6, 108, 43))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(30)
        self.key_17_name.setFont(font)
        self.key_17_name.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-style: solid;\n"
"border-width: 2px;\n"
"border-color: black;")
        self.key_17_name.setAlignment(QtCore.Qt.AlignCenter)
        self.key_17_name.setObjectName("key_17_name")
        self.checkBoxF = QtWidgets.QCheckBox(self.key17)
        self.checkBoxF.setGeometry(QtCore.QRect(600, 2, 51, 51))
        self.checkBoxF.setStyleSheet("QCheckBox::indicator {\n"
"     width: 40px;\n"
"     height: 40px;\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"    border-color: black;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
" background-color: rgb(7, 113, 240);\n"
"}\n"
"QCheckBox::indicator:unchecked {\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.checkBoxF.setText("")
        self.checkBoxF.setIconSize(QtCore.QSize(23, 28))
        self.checkBoxF.setCheckable(True)
        self.checkBoxF.setObjectName("checkBoxF")
        self.verticalLayout_2.addWidget(self.key17)
        self.key18 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.key18.sizePolicy().hasHeightForWidth())
        self.key18.setSizePolicy(sizePolicy)
        self.key18.setMinimumSize(QtCore.QSize(0, 55))
        self.key18.setMaximumSize(QtCore.QSize(16777215, 90))
        self.key18.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.key18.setStyleSheet("background-color: rgb(30, 217, 89);\n"
"")
        self.key18.setObjectName("key18")
        self.game_command18 = QtWidgets.QLineEdit(self.key18)
        self.game_command18.setGeometry(QtCore.QRect(10, 6, 251, 43))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.game_command18.sizePolicy().hasHeightForWidth())
        self.game_command18.setSizePolicy(sizePolicy)
        self.game_command18.setMinimumSize(QtCore.QSize(0, 43))
        self.game_command18.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(20)
        self.game_command18.setFont(font)
        self.game_command18.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"border-style: solid;\n"
"border-width: 2px;\n"
"border-color: black;")
        self.game_command18.setInputMask("")
        self.game_command18.setMaxLength(16)
        self.game_command18.setAlignment(QtCore.Qt.AlignCenter)
        self.game_command18.setObjectName("game_command18")
        self.key_18_name = QtWidgets.QLabel(self.key18)
        self.key_18_name.setGeometry(QtCore.QRect(336, 6, 108, 43))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(30)
        self.key_18_name.setFont(font)
        self.key_18_name.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-style: solid;\n"
"border-width: 2px;\n"
"border-color: black;")
        self.key_18_name.setAlignment(QtCore.Qt.AlignCenter)
        self.key_18_name.setObjectName("key_18_name")
        self.checkBox1 = QtWidgets.QCheckBox(self.key18)
        self.checkBox1.setGeometry(QtCore.QRect(600, 2, 51, 51))
        self.checkBox1.setStyleSheet("QCheckBox::indicator {\n"
"     width: 40px;\n"
"     height: 40px;\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"    border-color: black;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"   background-color: rgb(7, 113, 240);\n"
"}\n"
"QCheckBox::indicator:unchecked {\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.checkBox1.setText("")
        self.checkBox1.setIconSize(QtCore.QSize(23, 28))
        self.checkBox1.setCheckable(True)
        self.checkBox1.setObjectName("checkBox1")
        self.verticalLayout_2.addWidget(self.key18)
        self.key19 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.key19.sizePolicy().hasHeightForWidth())
        self.key19.setSizePolicy(sizePolicy)
        self.key19.setMinimumSize(QtCore.QSize(0, 55))
        self.key19.setMaximumSize(QtCore.QSize(16777215, 90))
        self.key19.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.key19.setStyleSheet("background-color: rgb(30, 217, 89);\n"
"")
        self.key19.setObjectName("key19")
        self.game_command19 = QtWidgets.QLineEdit(self.key19)
        self.game_command19.setGeometry(QtCore.QRect(10, 6, 251, 43))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.game_command19.sizePolicy().hasHeightForWidth())
        self.game_command19.setSizePolicy(sizePolicy)
        self.game_command19.setMinimumSize(QtCore.QSize(0, 43))
        self.game_command19.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(20)
        self.game_command19.setFont(font)
        self.game_command19.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"border-style: solid;\n"
"border-width: 2px;\n"
"border-color: black;")
        self.game_command19.setInputMask("")
        self.game_command19.setMaxLength(16)
        self.game_command19.setAlignment(QtCore.Qt.AlignCenter)
        self.game_command19.setObjectName("game_command19")
        self.key_19_name = QtWidgets.QLabel(self.key19)
        self.key_19_name.setGeometry(QtCore.QRect(336, 6, 108, 43))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(30)
        self.key_19_name.setFont(font)
        self.key_19_name.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-style: solid;\n"
"border-width: 2px;\n"
"border-color: black;")
        self.key_19_name.setAlignment(QtCore.Qt.AlignCenter)
        self.key_19_name.setObjectName("key_19_name")
        self.checkBox2 = QtWidgets.QCheckBox(self.key19)
        self.checkBox2.setGeometry(QtCore.QRect(600, 2, 51, 51))
        self.checkBox2.setStyleSheet("QCheckBox::indicator {\n"
"     width: 40px;\n"
"     height: 40px;\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"    border-color: black;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"   background-color: rgb(7, 113, 240);\n"
"}\n"
"QCheckBox::indicator:unchecked {\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.checkBox2.setText("")
        self.checkBox2.setIconSize(QtCore.QSize(23, 28))
        self.checkBox2.setCheckable(True)
        self.checkBox2.setObjectName("checkBox2")
        self.verticalLayout_2.addWidget(self.key19)
        self.key20 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.key20.sizePolicy().hasHeightForWidth())
        self.key20.setSizePolicy(sizePolicy)
        self.key20.setMinimumSize(QtCore.QSize(0, 55))
        self.key20.setMaximumSize(QtCore.QSize(16777215, 90))
        self.key20.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.key20.setStyleSheet("background-color: rgb(30, 217, 89);\n"
"")
        self.key20.setObjectName("key20")
        self.game_command20 = QtWidgets.QLineEdit(self.key20)
        self.game_command20.setGeometry(QtCore.QRect(10, 6, 251, 43))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.game_command20.sizePolicy().hasHeightForWidth())
        self.game_command20.setSizePolicy(sizePolicy)
        self.game_command20.setMinimumSize(QtCore.QSize(0, 43))
        self.game_command20.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(20)
        self.game_command20.setFont(font)
        self.game_command20.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"border-style: solid;\n"
"border-width: 2px;\n"
"border-color: black;")
        self.game_command20.setInputMask("")
        self.game_command20.setMaxLength(16)
        self.game_command20.setAlignment(QtCore.Qt.AlignCenter)
        self.game_command20.setObjectName("game_command20")
        self.key_20_name = QtWidgets.QLabel(self.key20)
        self.key_20_name.setGeometry(QtCore.QRect(336, 6, 108, 43))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(30)
        self.key_20_name.setFont(font)
        self.key_20_name.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-style: solid;\n"
"border-width: 2px;\n"
"border-color: black;")
        self.key_20_name.setAlignment(QtCore.Qt.AlignCenter)
        self.key_20_name.setObjectName("key_20_name")
        self.checkBox3 = QtWidgets.QCheckBox(self.key20)
        self.checkBox3.setGeometry(QtCore.QRect(600, 2, 51, 51))
        self.checkBox3.setStyleSheet("QCheckBox::indicator {\n"
"     width: 40px;\n"
"     height: 40px;\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"    border-color: black;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"  background-color: rgb(7, 113, 240);\n"
"}\n"
"QCheckBox::indicator:unchecked {\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.checkBox3.setText("")
        self.checkBox3.setIconSize(QtCore.QSize(23, 28))
        self.checkBox3.setCheckable(True)
        self.checkBox3.setObjectName("checkBox3")
        self.verticalLayout_2.addWidget(self.key20)
        self.key21 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.key21.sizePolicy().hasHeightForWidth())
        self.key21.setSizePolicy(sizePolicy)
        self.key21.setMinimumSize(QtCore.QSize(0, 55))
        self.key21.setMaximumSize(QtCore.QSize(16777215, 90))
        self.key21.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.key21.setStyleSheet("background-color: rgb(30, 217, 89);\n"
"")
        self.key21.setObjectName("key21")
        self.game_command21 = QtWidgets.QLineEdit(self.key21)
        self.game_command21.setGeometry(QtCore.QRect(10, 6, 251, 43))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.game_command21.sizePolicy().hasHeightForWidth())
        self.game_command21.setSizePolicy(sizePolicy)
        self.game_command21.setMinimumSize(QtCore.QSize(0, 43))
        self.game_command21.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(20)
        self.game_command21.setFont(font)
        self.game_command21.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"border-style: solid;\n"
"border-width: 2px;\n"
"border-color: black;")
        self.game_command21.setInputMask("")
        self.game_command21.setMaxLength(16)
        self.game_command21.setAlignment(QtCore.Qt.AlignCenter)
        self.game_command21.setObjectName("game_command21")
        self.key_21_name = QtWidgets.QLabel(self.key21)
        self.key_21_name.setGeometry(QtCore.QRect(336, 6, 108, 43))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(30)
        self.key_21_name.setFont(font)
        self.key_21_name.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-style: solid;\n"
"border-width: 2px;\n"
"border-color: black;")
        self.key_21_name.setAlignment(QtCore.Qt.AlignCenter)
        self.key_21_name.setObjectName("key_21_name")
        self.checkBox4 = QtWidgets.QCheckBox(self.key21)
        self.checkBox4.setGeometry(QtCore.QRect(600, 2, 51, 51))
        self.checkBox4.setStyleSheet("QCheckBox::indicator {\n"
"     width: 40px;\n"
"     height: 40px;\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"    border-color: black;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"   background-color: rgb(7, 113, 240);\n"
"}\n"
"QCheckBox::indicator:unchecked {\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.checkBox4.setText("")
        self.checkBox4.setIconSize(QtCore.QSize(23, 28))
        self.checkBox4.setCheckable(True)
        self.checkBox4.setObjectName("checkBox4")
        self.verticalLayout_2.addWidget(self.key21)
        self.key22 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.key22.sizePolicy().hasHeightForWidth())
        self.key22.setSizePolicy(sizePolicy)
        self.key22.setMinimumSize(QtCore.QSize(0, 55))
        self.key22.setMaximumSize(QtCore.QSize(16777215, 90))
        self.key22.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.key22.setStyleSheet("background-color: rgb(30, 217, 89);\n"
"")
        self.key22.setObjectName("key22")
        self.game_command22 = QtWidgets.QLineEdit(self.key22)
        self.game_command22.setGeometry(QtCore.QRect(10, 6, 251, 43))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.game_command22.sizePolicy().hasHeightForWidth())
        self.game_command22.setSizePolicy(sizePolicy)
        self.game_command22.setMinimumSize(QtCore.QSize(0, 43))
        self.game_command22.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(20)
        self.game_command22.setFont(font)
        self.game_command22.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"border-style: solid;\n"
"border-width: 2px;\n"
"border-color: black;")
        self.game_command22.setInputMask("")
        self.game_command22.setMaxLength(16)
        self.game_command22.setAlignment(QtCore.Qt.AlignCenter)
        self.game_command22.setObjectName("game_command22")
        self.key_22_name = QtWidgets.QLabel(self.key22)
        self.key_22_name.setGeometry(QtCore.QRect(336, 6, 108, 43))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(30)
        self.key_22_name.setFont(font)
        self.key_22_name.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-style: solid;\n"
"border-width: 2px;\n"
"border-color: black;")
        self.key_22_name.setAlignment(QtCore.Qt.AlignCenter)
        self.key_22_name.setObjectName("key_22_name")
        self.checkBox5 = QtWidgets.QCheckBox(self.key22)
        self.checkBox5.setGeometry(QtCore.QRect(600, 2, 51, 51))
        self.checkBox5.setStyleSheet("QCheckBox::indicator {\n"
"     width: 40px;\n"
"     height: 40px;\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"    border-color: black;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"  background-color: rgb(7, 113, 240);\n"
"}\n"
"QCheckBox::indicator:unchecked {\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.checkBox5.setText("")
        self.checkBox5.setIconSize(QtCore.QSize(23, 28))
        self.checkBox5.setCheckable(True)
        self.checkBox5.setObjectName("checkBox5")
        self.verticalLayout_2.addWidget(self.key22)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.name_title = QtWidgets.QLabel(Menu)
        self.name_title.setGeometry(QtCore.QRect(20, 88, 91, 51))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(18)
        self.name_title.setFont(font)
        self.name_title.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);\n"
"border-top-left-radius:7px;\n"
"border-bottom-left-radius: 7px;")
        self.name_title.setAlignment(QtCore.Qt.AlignCenter)
        self.name_title.setObjectName("name_title")
        self.game_name_area = QtWidgets.QLineEdit(Menu)
        self.game_name_area.setGeometry(QtCore.QRect(110, 88, 411, 52))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.game_name_area.sizePolicy().hasHeightForWidth())
        self.game_name_area.setSizePolicy(sizePolicy)
        self.game_name_area.setMinimumSize(QtCore.QSize(0, 52))
        self.game_name_area.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(20)
        self.game_name_area.setFont(font)
        self.game_name_area.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.game_name_area.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"border-left:0px;\n"
"border-left-width:0px;")
        self.game_name_area.setInputMask("")
        self.game_name_area.setMaxLength(25)
        self.game_name_area.setObjectName("game_name_area")
        self.comand_name = QtWidgets.QLabel(Menu)
        self.comand_name.setGeometry(QtCore.QRect(100, 162, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(23)
        self.comand_name.setFont(font)
        self.comand_name.setStyleSheet("color: rgb(255, 255, 255);")
        self.comand_name.setObjectName("comand_name")
        self.keys_name = QtWidgets.QLabel(Menu)
        self.keys_name.setGeometry(QtCore.QRect(370, 162, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(23)
        self.keys_name.setFont(font)
        self.keys_name.setStyleSheet("color: rgb(255, 255, 255);")
        self.keys_name.setAlignment(QtCore.Qt.AlignCenter)
        self.keys_name.setObjectName("keys_name")
        self.keep_pressing = QtWidgets.QLabel(Menu)
        self.keep_pressing.setGeometry(QtCore.QRect(546, 162, 251, 41))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(23)
        self.keep_pressing.setFont(font)
        self.keep_pressing.setStyleSheet("color: rgb(255, 255, 255);")
        self.keep_pressing.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.keep_pressing.setObjectName("keep_pressing")
        self.menu_button = QtWidgets.QPushButton(Menu)
        self.menu_button.setGeometry(QtCore.QRect(30, 610, 125, 51))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(16)
        self.menu_button.setFont(font)
        self.menu_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.menu_button.setStyleSheet("QPushButton{\n"
"    background-color: white;\n"
"    border-style: outset;\n"
"    border-radius: 10px;    \n"
"    padding: 6px;\n"
"}\n"
"QPushButton:pressed {\n"
"    \n"
"    background-color: rgb(199, 199, 199);\n"
"    border-style: inset;\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("image/left_arrow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menu_button.setIcon(icon)
        self.menu_button.setIconSize(QtCore.QSize(35, 35))
        self.menu_button.setObjectName("menu_button")
        self.apply_button = QtWidgets.QPushButton(Menu)
        self.apply_button.setGeometry(QtCore.QRect(740, 610, 125, 51))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(16)
        self.apply_button.setFont(font)
        self.apply_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.apply_button.setStyleSheet("QPushButton{\n"
"    background-color: white;\n"
"    border-style: outset;\n"
"    border-radius: 10px;    \n"
"    padding: 6px;\n"
"}\n"
"QPushButton:pressed {\n"
"    \n"
"    background-color: rgb(199, 199, 199);\n"
"    border-style: inset;\n"
"}\n"
"\n"
"")
        self.apply_button.setIconSize(QtCore.QSize(21, 21))
        self.apply_button.setObjectName("apply_button")
        self.repeated_commands = QtWidgets.QFrame(Menu)
        self.repeated_commands.setGeometry(QtCore.QRect(550, 70, 261, 91))
        self.repeated_commands.setStyleSheet("/* VERTIVAL SCROLL BAR*/\n"
"QScrollBar:vertical{\n"
"    boder: none;\n"
"    width: 14px;\n"
"    margin: 15px 0 15px 0;\n"
"    border-radius:10px;\n"
"    background-color: rgb(255, 0, 0);\n"
"}\n"
"\n"
"/* HANDLE BAR VERTICAL */\n"
"QScrollBar::handle:vertical {\n"
"    border-radius:4px;\n"
"    min-height:15px;\n"
"    background-color: rgb(31, 79, 108);\n"
"}\n"
"\n"
"/* BUTTON TOP - SCROLLBAR*/\n"
"\n"
"QScrollBar::sub-line:vertical{\n"
"    border:none;    \n"
"    background-color: rgb(255, 255, 255);\n"
"    height: 15px;\n"
"    border-top-left-radius: 5px;\n"
"    border-top-right-radius:5px;\n"
"    subcontrol-position:top;\n"
"    subcontrol-origin: margin;\n"
"    \n"
"}\n"
"\n"
"\n"
"\n"
"/* BUTTON BOTTOM - SCROLLBAR*/\n"
"\n"
"QScrollBar::add-line:vertical{\n"
"    border:none;    \n"
"    background-color: rgb(255, 255, 255);\n"
"    height: 15px;\n"
"    border-bottom-left-radius: 5px;\n"
"    border-bottom-right-radius:5px;\n"
"    subcontrol-position:bottom;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"\n"
"\n"
"/* RESET ARROW */\n"
"\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"     \n"
"     background: none;\n"
"}\n"
"\n"
" QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"     background: none;\n"
"}\n"
"\n"
"QScrollBar::sub-page:vertical {\n"
"background: none;\n"
"}\n"
"\n"
"QScrollBar::add-page:vertical {\n"
"background: none;\n"
"}\n"
"\n"
"")
        self.repeated_commands.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.repeated_commands.setFrameShadow(QtWidgets.QFrame.Plain)
        self.repeated_commands.setLineWidth(0)
        self.repeated_commands.setObjectName("repeated_commands")
        self.scrollArea2 = QtWidgets.QScrollArea(self.repeated_commands)
        self.scrollArea2.setGeometry(QtCore.QRect(-1, 10, 262, 81))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea2.sizePolicy().hasHeightForWidth())
        self.scrollArea2.setSizePolicy(sizePolicy)
        self.scrollArea2.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.scrollArea2.setStyleSheet("/* VERTIVAL SCROLL BAR*/\n"
"QScrollBar:vertical{\n"
"    \n"
"    background-color: rgb(255, 0, 0);\n"
"}\n"
"\n"
"\n"
"\n"
"")
        self.scrollArea2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.scrollArea2.setLineWidth(0)
        self.scrollArea2.setWidgetResizable(True)
        self.scrollArea2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.scrollArea2.setObjectName("scrollArea2")
        self.scrollAreaWidgetContents2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents2.setGeometry(QtCore.QRect(0, 0, 262, 36))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents2.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents2.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.scrollAreaWidgetContents2.setObjectName("scrollAreaWidgetContents2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents2)
        self.verticalLayout_4.setContentsMargins(9, 6, 9, 0)
        self.verticalLayout_4.setSpacing(12)
        self.verticalLayout_4.setObjectName("verticalLayout_4")

        self.scrollArea2.setWidget(self.scrollAreaWidgetContents2)
        self.frame.raise_()
        self.Title_Screen.raise_()
        self.name_title.raise_()
        self.game_name_area.raise_()
        self.comand_name.raise_()
        self.keys_name.raise_()
        self.keep_pressing.raise_()
        self.menu_button.raise_()
        self.apply_button.raise_()
        self.repeated_commands.raise_()

        self.retranslateUi(Menu)
        QtCore.QMetaObject.connectSlotsByName(Menu)

    def retranslateUi(self, Menu):
        _translate = QtCore.QCoreApplication.translate
        Menu.setWindowTitle(_translate("Menu", "Menu"))
        self.Title_Screen.setText(_translate("Menu", "Configurações de jogo"))
        self.key_1_name.setText(_translate("Menu", "W"))
        self.key_2_name.setText(_translate("Menu", "S"))
        self.key_3_name.setText(_translate("Menu", "A"))
        self.key_4_name.setText(_translate("Menu", "D"))
        self.key_5_name.setText(_translate("Menu", "Q"))
        self.key_6_name.setText(_translate("Menu", "E"))
        self.key_7_name.setText(_translate("Menu", "R"))
        self.key_8_name.setText(_translate("Menu", "T"))
        self.key_10_name.setText(_translate("Menu", "Ctrl"))
        self.key_12_name.setText(_translate("Menu", "Tab"))
        self.key_13_name.setText(_translate("Menu", "Z"))
        self.key_14_name.setText(_translate("Menu", "X"))
        self.key_15_name.setText(_translate("Menu", "C"))
        self.key_16_name.setText(_translate("Menu", "V"))
        self.key_17_name.setText(_translate("Menu", "F"))
        self.key_18_name.setText(_translate("Menu", "1"))
        self.key_19_name.setText(_translate("Menu", "2"))
        self.key_20_name.setText(_translate("Menu", "3"))
        self.key_21_name.setText(_translate("Menu", "4"))
        self.key_22_name.setText(_translate("Menu", "5"))
        self.name_title.setText(_translate("Menu", "Nome:"))
        self.comand_name.setText(_translate("Menu", "Comando"))
        self.keys_name.setText(_translate("Menu", "Tecla"))
        self.keep_pressing.setText(_translate("Menu", "Manter Pressionado"))
        self.menu_button.setText(_translate("Menu", "  Voltar"))
        self.apply_button.setText(_translate("Menu", "Salvar"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Menu = QtWidgets.QWidget()
    ui = Ui_Edit()
    ui.setupUi(Menu)
    Menu.show()
    sys.exit(app.exec_())
