# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'instruction.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Instruction(object):
    def setupUi(self, Menu):
        Menu.setObjectName("Menu")
        Menu.setWindowModality(QtCore.Qt.ApplicationModal)
        Menu.resize(885, 677)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Menu.sizePolicy().hasHeightForWidth())
        Menu.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(49)
        Menu.setFont(font)
        Menu.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        Menu.setAutoFillBackground(False)
        Menu.setStyleSheet("QWidget {    \n"
"\n"
"    \n"
"    background-color: rgb(26, 65, 90);\n"
"\n"
"}\n"
"/*\n"
"\n"
"background-image: linear-gradient(15deg, #13547a 0%, #80d0c7 100%);\n"
"background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #13547a, stop: .5 #80d0c7);\n"
"background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0.4 #13547a, stop: 0.8 #80d0c7);\n"
"            \n"
"\n"
"*/\n"
"\n"
"/* background-color: rgb(26, 65, 90); */\n"
"\n"
"\n"
"")
        self.Title_Screen = QtWidgets.QLabel(Menu)
        self.Title_Screen.setGeometry(QtCore.QRect(220, 0, 461, 61))
        font = QtGui.QFont()
        font.setFamily("Leelawadee")
        font.setPointSize(32)
        self.Title_Screen.setFont(font)
        self.Title_Screen.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Title_Screen.setAutoFillBackground(False)
        self.Title_Screen.setStyleSheet("color: rgb(255, 255, 255);\n"
"boder:none;")
        self.Title_Screen.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Title_Screen.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Title_Screen.setLineWidth(0)
        self.Title_Screen.setAlignment(QtCore.Qt.AlignCenter)
        self.Title_Screen.setObjectName("Title_Screen")
        self.frame = QtWidgets.QFrame(Menu)
        self.frame.setGeometry(QtCore.QRect(28, 69, 831, 511))
        self.frame.setStyleSheet("/* VERTIVAL SCROLL BAR*/\n"
"QScrollBar:vertical{\n"
"    boder: none;\n"
"    width: 14px;\n"
"    margin: 15px 0 15px 0;\n"
"    border-radius:10px;\n"
"    background-color: rgb(31, 125, 108);\n"
"}\n"
"\n"
"/* HANDLE BAR VERTICAL */\n"
"QScrollBar::handle:vertical {\n"
"    border-radius:4px;\n"
"    min-height:15px;\n"
"    background-color: rgb(31, 79, 108);\n"
"}\n"
"\n"
"/* BUTTON TOP - SCROLLBAR*/\n"
"\n"
"QScrollBar::sub-line:vertical{\n"
"    background-color: rgb(255, 255, 255);\n"
"    height: 15px;\n"
"    border-top-left-radius: 5px;\n"
"    border-top-right-radius:5px;\n"
"    subcontrol-position:top;\n"
"    subcontrol-origin: margin;\n"
"    \n"
"}\n"
"\n"
"/* BUTTON BOTTOM - SCROLLBAR*/\n"
"\n"
"QScrollBar::add-line:vertical{\n"
"    background-color: rgb(255, 255, 255);\n"
"    height: 15px;\n"
"    border-bottom-left-radius: 5px;\n"
"    border-bottom-right-radius:5px;\n"
"    subcontrol-position:bottom;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"/* RESET ARROW */\n"
"\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {     \n"
"     background: none;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"     background: none;\n"
"}\n"
"\n"
"QScrollBar::sub-page:vertical {\n"
"background: none;\n"
"}\n"
"\n"
"QScrollBar::add-page:vertical {\n"
"background: none;\n"
"}\n"
"\n"
"QWidget {\n"
"\n"
"    background-color: transparent;\n"
"\n"
"}\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setLineWidth(0)
        self.frame.setObjectName("frame")
        self.scrollArea = QtWidgets.QScrollArea(self.frame)
        self.scrollArea.setGeometry(QtCore.QRect(0, 0, 831, 511))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.scrollArea.setStyleSheet("/* VERTIVAL SCROLL BAR*/\n"
"QScrollBar:vertical{\n"
"    background-color: rgb(31, 125, 108);\n"
"}\n"
"\n"
"\n"
"\n"
"")
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setFrameShadow(QtWidgets.QFrame.Plain)
        self.scrollArea.setLineWidth(0)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 817, 2074))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setContentsMargins(9, 10, 9, 0)
        self.verticalLayout_2.setSpacing(20)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.slide1 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.slide1.sizePolicy().hasHeightForWidth())
        self.slide1.setSizePolicy(sizePolicy)
        self.slide1.setMinimumSize(QtCore.QSize(651, 501))
        self.slide1.setText("")
        self.slide1.setPixmap(QtGui.QPixmap("image/Instrução_Slide_Menu.png"))
        self.slide1.setScaledContents(True)
        self.slide1.setObjectName("slide1")
        self.verticalLayout_2.addWidget(self.slide1)
        self.slide1_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.slide1_4.sizePolicy().hasHeightForWidth())
        self.slide1_4.setSizePolicy(sizePolicy)
        self.slide1_4.setMinimumSize(QtCore.QSize(651, 501))
        self.slide1_4.setText("")
        self.slide1_4.setPixmap(QtGui.QPixmap("image/Instrução_ReconhecimentoDeVoz_Slides.png"))
        self.slide1_4.setScaledContents(True)
        self.slide1_4.setObjectName("slide1_4")
        self.verticalLayout_2.addWidget(self.slide1_4)
        self.slide1_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.slide1_2.sizePolicy().hasHeightForWidth())
        self.slide1_2.setSizePolicy(sizePolicy)
        self.slide1_2.setMinimumSize(QtCore.QSize(651, 501))
        self.slide1_2.setText("")
        self.slide1_2.setPixmap(QtGui.QPixmap("image/Instrução_Slides_Edit_Screen01.png"))
        self.slide1_2.setScaledContents(True)
        self.slide1_2.setObjectName("slide1_2")
        self.verticalLayout_2.addWidget(self.slide1_2)
        self.slide1_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.slide1_3.sizePolicy().hasHeightForWidth())
        self.slide1_3.setSizePolicy(sizePolicy)
        self.slide1_3.setMinimumSize(QtCore.QSize(651, 501))
        self.slide1_3.setText("")
        self.slide1_3.setPixmap(QtGui.QPixmap("image/Instrução_Slides_Edit_Screen02.png"))
        self.slide1_3.setScaledContents(True)
        self.slide1_3.setObjectName("slide1_3")
        self.verticalLayout_2.addWidget(self.slide1_3)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.menu_button = QtWidgets.QPushButton(Menu)
        self.menu_button.setGeometry(QtCore.QRect(30, 610, 125, 51))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(16)
        self.menu_button.setFont(font)
        self.menu_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.menu_button.setStyleSheet("QPushButton{\n"
"    background-color: white;\n"
"    border-radius: 10px;    \n"
"    padding: 6px;\n"
"}\n"
"QPushButton:pressed {\n"
"    \n"
"    background-color: rgb(199, 199, 199);\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("image/left_arrow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menu_button.setIcon(icon)
        self.menu_button.setIconSize(QtCore.QSize(35, 35))
        self.menu_button.setObjectName("menu_button")
        self.frame.raise_()
        self.Title_Screen.raise_()
        self.menu_button.raise_()

        self.retranslateUi(Menu)
        QtCore.QMetaObject.connectSlotsByName(Menu)

    def retranslateUi(self, Menu):
        _translate = QtCore.QCoreApplication.translate
        Menu.setWindowTitle(_translate("Menu", "Menu"))
        self.Title_Screen.setText(_translate("Menu", "Instrução"))
        self.menu_button.setText(_translate("Menu", "  Voltar"))


