# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Menu(object):
    def setupUi(self, Menu):
        Menu.setObjectName("Menu")
        Menu.setWindowModality(QtCore.Qt.ApplicationModal)
        Menu.resize(885, 667)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Menu.sizePolicy().hasHeightForWidth())
        Menu.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(49)
        Menu.setFont(font)
        Menu.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        Menu.setAutoFillBackground(False)
        Menu.setStyleSheet("QWidget {    \n"
"\n"
"    \n"
"    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0.4 #13547a, stop: 0.8 #80d0c7);\n"
"        \n"
"\n"
"}\n"
"/*\n"
"\n"
"background-image: linear-gradient(15deg, #13547a 0%, #80d0c7 100%);\n"
"background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #13547a, stop: .5 #80d0c7);\n"
"    \n"
"\n"
"*/\n"
"\n"
"/* background-color: rgb(26, 65, 90); */\n"
"\n"
"\n"
"")
        self.Title_Software = QtWidgets.QLabel(Menu)
        self.Title_Software.setGeometry(QtCore.QRect(220, 10, 471, 81))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(41)
        self.Title_Software.setFont(font)
        self.Title_Software.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Title_Software.setAutoFillBackground(False)
        self.Title_Software.setStyleSheet("background-color: rgb(19, 84, 122);\n"
"color: rgb(255, 255, 255);\n"
"boder:none;")
        self.Title_Software.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Title_Software.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Title_Software.setLineWidth(0)
        self.Title_Software.setAlignment(QtCore.Qt.AlignCenter)
        self.Title_Software.setObjectName("Title_Software")
        self.addButton = QtWidgets.QPushButton(Menu)
        self.addButton.setGeometry(QtCore.QRect(40, 80, 61, 51))
        self.addButton.setStyleSheet("background-color: rgb(19, 84, 122);\n"
"border:none;\n"
"border-width:0px;\n"
"\n"
"")
        self.addButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Images/add_button.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.addButton.setIcon(icon)
        self.addButton.setIconSize(QtCore.QSize(51, 49))
        self.addButton.setDefault(False)
        self.addButton.setObjectName("addButton")
        self.frame = QtWidgets.QFrame(Menu)
        self.frame.setGeometry(QtCore.QRect(120, 145, 681, 451))
        self.frame.setStyleSheet("/* VERTIVAL SCROLL BAR*/\n"
"QScrollBar:vertical{\n"
"    boder: none;\n"
"    width: 14px;\n"
"    margin: 15px 0 15px 0;\n"
"    border-radius:10px;\n"
"    background-color: rgb(31, 125, 108);\n"
"}\n"
"\n"
"/* HANDLE BAR VERTICAL */\n"
"QScrollBar::handle:vertical {\n"
"    border-radius:4px;\n"
"    min-height:15px;\n"
"    background-color: rgb(31, 79, 108);\n"
"}\n"
"\n"
"/* BUTTON TOP - SCROLLBAR*/\n"
"\n"
"QScrollBar::sub-line:vertical{\n"
"    border:none;    \n"
"    background-color: rgb(255, 255, 255);\n"
"    height: 15px;\n"
"    border-top-left-radius: 5px;\n"
"    border-top-right-radius:5px;\n"
"    subcontrol-position:top;\n"
"    subcontrol-origin: margin;\n"
"    \n"
"}\n"
"\n"
"\n"
"\n"
"/* BUTTON BOTTOM - SCROLLBAR*/\n"
"\n"
"QScrollBar::add-line:vertical{\n"
"    border:none;    \n"
"    background-color: rgb(255, 255, 255);\n"
"    height: 15px;\n"
"    border-bottom-left-radius: 5px;\n"
"    border-bottom-right-radius:5px;\n"
"    subcontrol-position:bottom;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"\n"
"\n"
"/* RESET ARROW */\n"
"\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"     \n"
"     background: none;\n"
"}\n"
"\n"
" QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"     background: none;\n"
"}\n"
"\n"
"QScrollBar::sub-page:vertical {\n"
"background: none;\n"
"}\n"
"\n"
"QScrollBar::add-page:vertical {\n"
"background: none;\n"
"}\n"
"\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.VLine)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setLineWidth(0)
        self.frame.setObjectName("frame")
        self.scrollArea = QtWidgets.QScrollArea(self.frame)
        self.scrollArea.setGeometry(QtCore.QRect(-1, 0, 681, 451))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.scrollArea.setStyleSheet("/* VERTIVAL SCROLL BAR*/\n"
"QScrollBar:vertical{\n"
"    background-color: rgb(31, 125, 108);\n"
"}\n"
"\n"
"\n"
"\n"
"")
        self.scrollArea.setFrameShape(QtWidgets.QFrame.VLine)
        self.scrollArea.setFrameShadow(QtWidgets.QFrame.Plain)
        self.scrollArea.setLineWidth(0)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, -86, 667, 537))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setContentsMargins(-1, 10, -1, 0)
        self.verticalLayout_2.setSpacing(25)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.jogo6 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.jogo6.sizePolicy().hasHeightForWidth())
        self.jogo6.setSizePolicy(sizePolicy)
        self.jogo6.setMinimumSize(QtCore.QSize(0, 67))
        self.jogo6.setMaximumSize(QtCore.QSize(16777215, 90))
        self.jogo6.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.jogo6.setStyleSheet("background-color: rgb(30, 217, 89);\n"
"border-radius:15px;")
        self.jogo6.setObjectName("jogo6")
        self.game_name6 = QtWidgets.QLabel(self.jogo6)
        self.game_name6.setGeometry(QtCore.QRect(18, 1, 500, 61))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.game_name6.sizePolicy().hasHeightForWidth())
        self.game_name6.setSizePolicy(sizePolicy)
        self.game_name6.setMaximumSize(QtCore.QSize(500, 90))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(36)
        self.game_name6.setFont(font)
        self.game_name6.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.game_name6.setStyleSheet("color: rgb(255, 255, 255);")
        self.game_name6.setObjectName("game_name6")
        self.edit_button6 = QtWidgets.QPushButton(self.jogo6)
        self.edit_button6.setGeometry(QtCore.QRect(520, 8, 51, 51))
        self.edit_button6.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.edit_button6.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Images/edit_button.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.edit_button6.setIcon(icon1)
        self.edit_button6.setIconSize(QtCore.QSize(50, 50))
        self.edit_button6.setObjectName("edit_button6")
        self.play_button6 = QtWidgets.QPushButton(self.jogo6)
        self.play_button6.setGeometry(QtCore.QRect(588, 11, 51, 51))
        self.play_button6.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.play_button6.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("Images/play_button3.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.play_button6.setIcon(icon2)
        self.play_button6.setIconSize(QtCore.QSize(50, 50))
        self.play_button6.setObjectName("play_button6")
        self.verticalLayout_2.addWidget(self.jogo6)
        self.jogo5 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.jogo5.sizePolicy().hasHeightForWidth())
        self.jogo5.setSizePolicy(sizePolicy)
        self.jogo5.setMinimumSize(QtCore.QSize(0, 67))
        self.jogo5.setMaximumSize(QtCore.QSize(16777215, 90))
        self.jogo5.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.jogo5.setStyleSheet("background-color: rgb(30, 217, 89);\n"
"border-radius:15px;")
        self.jogo5.setObjectName("jogo5")
        self.game_name5 = QtWidgets.QLabel(self.jogo5)
        self.game_name5.setGeometry(QtCore.QRect(18, 1, 500, 61))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.game_name5.sizePolicy().hasHeightForWidth())
        self.game_name5.setSizePolicy(sizePolicy)
        self.game_name5.setMaximumSize(QtCore.QSize(500, 90))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(36)
        self.game_name5.setFont(font)
        self.game_name5.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.game_name5.setStyleSheet("color: rgb(255, 255, 255);")
        self.game_name5.setObjectName("game_name5")
        self.edit_button5 = QtWidgets.QPushButton(self.jogo5)
        self.edit_button5.setGeometry(QtCore.QRect(520, 8, 51, 51))
        self.edit_button5.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.edit_button5.setText("")
        self.edit_button5.setIcon(icon1)
        self.edit_button5.setIconSize(QtCore.QSize(50, 50))
        self.edit_button5.setObjectName("edit_button5")
        self.play_button5 = QtWidgets.QPushButton(self.jogo5)
        self.play_button5.setGeometry(QtCore.QRect(588, 11, 51, 51))
        self.play_button5.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.play_button5.setText("")
        self.play_button5.setIcon(icon2)
        self.play_button5.setIconSize(QtCore.QSize(50, 50))
        self.play_button5.setObjectName("play_button5")
        self.verticalLayout_2.addWidget(self.jogo5)
        self.jogo4 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.jogo4.sizePolicy().hasHeightForWidth())
        self.jogo4.setSizePolicy(sizePolicy)
        self.jogo4.setMinimumSize(QtCore.QSize(0, 67))
        self.jogo4.setMaximumSize(QtCore.QSize(16777215, 90))
        self.jogo4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.jogo4.setStyleSheet("background-color: rgb(30, 217, 89);\n"
"border-radius:15px;")
        self.jogo4.setObjectName("jogo4")
        self.game_name4 = QtWidgets.QLabel(self.jogo4)
        self.game_name4.setGeometry(QtCore.QRect(18, 1, 500, 61))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.game_name4.sizePolicy().hasHeightForWidth())
        self.game_name4.setSizePolicy(sizePolicy)
        self.game_name4.setMaximumSize(QtCore.QSize(500, 90))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(36)
        self.game_name4.setFont(font)
        self.game_name4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.game_name4.setStyleSheet("color: rgb(255, 255, 255);")
        self.game_name4.setObjectName("game_name4")
        self.edit_button4 = QtWidgets.QPushButton(self.jogo4)
        self.edit_button4.setGeometry(QtCore.QRect(520, 8, 51, 51))
        self.edit_button4.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.edit_button4.setText("")
        self.edit_button4.setIcon(icon1)
        self.edit_button4.setIconSize(QtCore.QSize(50, 50))
        self.edit_button4.setObjectName("edit_button4")
        self.play_button4 = QtWidgets.QPushButton(self.jogo4)
        self.play_button4.setGeometry(QtCore.QRect(588, 11, 51, 51))
        self.play_button4.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.play_button4.setText("")
        self.play_button4.setIcon(icon2)
        self.play_button4.setIconSize(QtCore.QSize(50, 50))
        self.play_button4.setObjectName("play_button4")
        self.verticalLayout_2.addWidget(self.jogo4)
        self.jogo3 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.jogo3.sizePolicy().hasHeightForWidth())
        self.jogo3.setSizePolicy(sizePolicy)
        self.jogo3.setMinimumSize(QtCore.QSize(0, 67))
        self.jogo3.setMaximumSize(QtCore.QSize(16777215, 90))
        self.jogo3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.jogo3.setStyleSheet("background-color: rgb(30, 217, 89);\n"
"border-radius:15px;")
        self.jogo3.setObjectName("jogo3")
        self.game_name3 = QtWidgets.QLabel(self.jogo3)
        self.game_name3.setGeometry(QtCore.QRect(18, 1, 500, 61))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.game_name3.sizePolicy().hasHeightForWidth())
        self.game_name3.setSizePolicy(sizePolicy)
        self.game_name3.setMaximumSize(QtCore.QSize(500, 90))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(36)
        self.game_name3.setFont(font)
        self.game_name3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.game_name3.setStyleSheet("color: rgb(255, 255, 255);")
        self.game_name3.setObjectName("game_name3")
        self.edit_button3 = QtWidgets.QPushButton(self.jogo3)
        self.edit_button3.setGeometry(QtCore.QRect(520, 8, 51, 51))
        self.edit_button3.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.edit_button3.setText("")
        self.edit_button3.setIcon(icon1)
        self.edit_button3.setIconSize(QtCore.QSize(50, 50))
        self.edit_button3.setObjectName("edit_button3")
        self.play_button3 = QtWidgets.QPushButton(self.jogo3)
        self.play_button3.setGeometry(QtCore.QRect(588, 11, 51, 51))
        self.play_button3.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.play_button3.setText("")
        self.play_button3.setIcon(icon2)
        self.play_button3.setIconSize(QtCore.QSize(50, 50))
        self.play_button3.setObjectName("play_button3")
        self.verticalLayout_2.addWidget(self.jogo3)
        self.jogo2 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.jogo2.sizePolicy().hasHeightForWidth())
        self.jogo2.setSizePolicy(sizePolicy)
        self.jogo2.setMinimumSize(QtCore.QSize(0, 67))
        self.jogo2.setMaximumSize(QtCore.QSize(16777215, 90))
        self.jogo2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.jogo2.setStyleSheet("background-color: rgb(30, 217, 89);\n"
"border-radius:15px;")
        self.jogo2.setObjectName("jogo2")
        self.game_name2 = QtWidgets.QLabel(self.jogo2)
        self.game_name2.setGeometry(QtCore.QRect(18, 1, 500, 61))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.game_name2.sizePolicy().hasHeightForWidth())
        self.game_name2.setSizePolicy(sizePolicy)
        self.game_name2.setMaximumSize(QtCore.QSize(500, 90))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(36)
        self.game_name2.setFont(font)
        self.game_name2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.game_name2.setStyleSheet("color: rgb(255, 255, 255);")
        self.game_name2.setObjectName("game_name2")
        self.edit_button2 = QtWidgets.QPushButton(self.jogo2)
        self.edit_button2.setGeometry(QtCore.QRect(520, 8, 51, 51))
        self.edit_button2.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.edit_button2.setText("")
        self.edit_button2.setIcon(icon1)
        self.edit_button2.setIconSize(QtCore.QSize(50, 50))
        self.edit_button2.setObjectName("edit_button2")
        self.play_button2 = QtWidgets.QPushButton(self.jogo2)
        self.play_button2.setGeometry(QtCore.QRect(588, 11, 51, 51))
        self.play_button2.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.play_button2.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("Images/play_button.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.play_button2.setIcon(icon3)
        self.play_button2.setIconSize(QtCore.QSize(50, 50))
        self.play_button2.setObjectName("play_button2")
        self.verticalLayout_2.addWidget(self.jogo2)
        self.jogo1 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.jogo1.sizePolicy().hasHeightForWidth())
        self.jogo1.setSizePolicy(sizePolicy)
        self.jogo1.setMinimumSize(QtCore.QSize(0, 67))
        self.jogo1.setMaximumSize(QtCore.QSize(16777215, 90))
        self.jogo1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.jogo1.setStyleSheet("background-color: rgb(30, 217, 89);\n"
"border-radius:15px;")
        self.jogo1.setObjectName("jogo1")
        self.game_name = QtWidgets.QLabel(self.jogo1)
        self.game_name.setGeometry(QtCore.QRect(18, 1, 500, 61))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.game_name.sizePolicy().hasHeightForWidth())
        self.game_name.setSizePolicy(sizePolicy)
        self.game_name.setMaximumSize(QtCore.QSize(500, 90))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(36)
        self.game_name.setFont(font)
        self.game_name.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.game_name.setStyleSheet("color: rgb(255, 255, 255);")
        self.game_name.setObjectName("game_name")
        self.edit_button = QtWidgets.QPushButton(self.jogo1)
        self.edit_button.setGeometry(QtCore.QRect(520, 8, 51, 51))
        self.edit_button.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.edit_button.setText("")
        self.edit_button.setIcon(icon1)
        self.edit_button.setIconSize(QtCore.QSize(50, 50))
        self.edit_button.setObjectName("edit_button")
        self.play_button = QtWidgets.QPushButton(self.jogo1)
        self.play_button.setGeometry(QtCore.QRect(588, 11, 51, 51))
        self.play_button.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.play_button.setText("")
        self.play_button.setIcon(icon2)
        self.play_button.setIconSize(QtCore.QSize(50, 50))
        self.play_button.setObjectName("play_button")
        self.verticalLayout_2.addWidget(self.jogo1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.frame.raise_()
        self.Title_Software.raise_()
        self.addButton.raise_()

        self.retranslateUi(Menu)
        QtCore.QMetaObject.connectSlotsByName(Menu)

    def retranslateUi(self, Menu):
        _translate = QtCore.QCoreApplication.translate
        Menu.setWindowTitle(_translate("Menu", "Menu"))
        self.Title_Software.setText(_translate("Menu", "Speech 4 Gaming"))
        self.game_name6.setText(_translate("Menu", "Guitar Hero"))
        self.game_name5.setText(_translate("Menu", "Clone Heros"))
        self.game_name4.setText(_translate("Menu", "Fall Guy\'s"))
        self.game_name3.setText(_translate("Menu", "Apex Legends"))
        self.game_name2.setText(_translate("Menu", "League of Legends"))
        self.game_name.setText(_translate("Menu", "Super Mario Bros"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Menu = QtWidgets.QWidget()
    ui = Ui_Menu()
    ui.setupUi(Menu)
    Menu.show()
    sys.exit(app.exec_())
